This is makeindex, version 2.15 [TeX Live 2014] (kpathsea + Thai support).
Scanning style file ./detailed-design.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file detailed-design.acn....done (14 entries accepted, 0 rejected).
Sorting entries....done (58 comparisons).
Generating output file detailed-design.acr....done (25 lines written, 0 warnings).
Output written in detailed-design.acr.
Transcript written in detailed-design.alg.
